import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
const ROOT = join(process.cwd(), '..');
const MIME = { '.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json' };
const server = createServer(async (req,res)=>{ try{ let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/')p='/index.html'; const d=await readFile(join(ROOT,p)); res.writeHead(200,{'Content-Type':MIME[extname(p)]||'application/octet-stream'}); res.end(d);}catch{res.writeHead(404);res.end('404');}});
await new Promise(r=>server.listen(4633,r));
const b = await chromium.launch();
const pg = await (await b.newContext()).newPage();
pg.on('pageerror', e=>console.log('PAGEERROR:', e.message));
pg.on('console', m=>{ if(m.type()==='error') console.log('CONSOLE ERR:', m.text()); });
await pg.goto('http://localhost:4633/index.html', { waitUntil:'networkidle' });
await pg.waitForTimeout(500);
console.log('typeof openQR:', await pg.evaluate(()=>typeof openQR));
console.log('modal exists:', await pg.evaluate(()=>!!document.getElementById('qrModal')));
const r = await pg.evaluate(()=>{ try{ openQR(); return document.getElementById('qrModal').classList.contains('open'); }catch(e){ return 'ERR:'+e.message; } });
console.log('after openQR, open =', r);
await b.close(); server.close();
